# Generated by Django 2.0.4 on 2018-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='Question_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
