# Generated by Django 2.0.4 on 2018-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20180530_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='Question_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Question_images\\'),
        ),
    ]
