# Generated by Django 2.0.4 on 2018-05-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20180530_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestjunction',
            name='marks_obtained',
        ),
    ]
