# Generated by Django 2.0.4 on 2018-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_auto_20180622_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='Question_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
