# Generated by Django 2.0.4 on 2018-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_auto_20180705_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='Question',
            field=models.TextField(default='Test 1, Subject 4, Question 16', max_length=500),
        ),
    ]
