# Generated by Django 2.0.4 on 2018-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_auto_20180705_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextensiontable',
            name='last_session_key',
            field=models.CharField(default='asdasdasd', max_length=500),
            preserve_default=False,
        ),
    ]
