# Generated by Django 2.0.4 on 2018-07-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_userextensiontable_last_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextensiontable',
            name='last_session_key',
        ),
    ]
