# Generated by Django 2.0.4 on 2018-08-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_auto_20180802_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='Correct_option',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
